CREATE TABLE balance_account_types (
    type_id INTEGER NOT NULL PRIMARY KEY,
    type_name VARCHAR(50)
);

-- might put account balance in this table
CREATE TABLE balance_accounts (
    account_id INTEGER NOT NULL PRIMARY KEY,
    account_name VARCHAR(255) NOT NULL,
    account_type INTEGER NOT NULL,
    FOREIGN KEY (account_type) REFERENCES balance_account_types(type_id)
);

CREATE TABLE booking_records (
    record_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    reason VARCHAR(500),
    booking_date INTEGER, -- UNIX Timestamp
    debit_account_id INTEGER NOT NULL,
    credit_account_id INTEGER NOT NULL,
    amount MONEY NOT NULL,
    FOREIGN KEY (debit_account_id) REFERENCES balance_accounts(account_id),
    FOREIGN KEY (credit_account_id) REFERENCES balance_accounts(account_id)
);

INSERT INTO balance_account_types (type_id, type_name)
VALUES (1, 'active'), (2, 'passive');

INSERT INTO balance_accounts (account_id, account_name, account_type)
VALUES
    (100, 'Flüssige Mittel', 1),
    (1000, 'Kasse', 1),
    (1020, 'Bankguthaben', 1),
    (106, 'Kurzfristig gehaltene Aktiven mit Börsenkurs', 1),
    (1060, 'Wertschriften', 1),
    (1069, 'Wertberichtigungen Wertschriften', 1),
    (110, 'Forderungen aus Lieferungen und Leistungen', 1),
    (1100, 'Forderungen aus Lieferungen und Leistungen (Debitoren)', 1),
    (1109, 'Delkredere', 1),
    (114, 'Übrige kurzfristige Forderungen', 1),
    (1140, 'Vorschüsse und Darlehen', 1),
    (1149, 'Wertberichtigungen Vorschüsse und Darlehen', 1),
    (1170, 'Vorsteuer MWST Material, Waren, Dienstleistungen, Energie', 1),
    (1171, 'Vorsteuer MWST Investitionen, übriger Betriebsaufwand', 1),
    (1176, 'Verrechnungssteuer', 1),
    (1180, 'Forderungen gegenüber Sozialversicherungen und Vorsorgeeinrichtungen', 1),
    (1189, 'Quellensteuer', 1),
    (1190, 'Sonstige kurzfristige Forderungen', 1),
    (1199, 'Wertberichtigungen sonstige kurzfristige Forderungen', 1),
    (120, 'Vorräte und nicht fakturierte Dienstleistungen', 1),
    (1200, 'Handelswaren', 1),
    (1210, 'Rohstoffe', 1),
    (1220, 'Werkstoffe', 1),
    (1230, 'Hilfs- und Verbrauchsmaterial', 1),
    (1250, 'Handelswaren in Konsignation', 1),
    (1260, 'Fertige Erzeugnisse', 1),
    (1270, 'Unfertige Erzeugnisse', 1),
    (1280, 'Nicht fakturierte Dienstleistungen', 1),
    (130, 'Aktive Rechnungsabgrenzungen', 1),
    (1300, 'Bezahlter Aufwand des Folgejahres', 1),
    (1301, 'Noch nicht erhaltener Ertrag', 1),
    (140, 'Finanzanlagen', 1),
    (1400, 'Wertschriften', 1),
    (1409, 'Wertberichtigungen Wertschriften', 1),
    (1440, 'Darlehen', 1),
    (1441, 'Hypotheken', 1),
    (1449, 'Wertberichtigungen langfristige Forderungen', 1),
    (148, 'Beteiligungen', 1),
    (1480, 'Beteiligungen', 1),
    (1489, 'Wertberichtigungen Beteiligungen', 1),
    (150, 'Mobile Sachanlagen', 1),
    (1500, ' Mobile Sachanlagen', 1),
    (1509, 'Wertberichtigungen Maschinen und Apparate', 1),
    (1510, 'Mobiliar und Einrichtungen', 1),
    (1519, 'Wertberichtigungen Mobiliar und Einrichtungen', 1),
    (1520, 'Büromaschinen, Informatik, Kommunikationstechnologie', 1),
    (1529, 'Wertberichtigungen Büromaschinen, Informatik, Kommunikationstechnologie', 1),
    (1530, 'Fahrzeuge', 1),
    (1539, 'Wertberichtigungen Fahrzeuge', 1),
    (1540, 'Werkzeuge und Geräte', 1),
    (1549, 'Wertberichtigungen Werkzeuge und Geräte', 1),
    (160, 'Immobile Sachanlagen', 1),
    (1600, 'Geschäftsliegenschaften', 1),
    (1609, 'Wertberichtigungen Geschäftsliegenschaften', 1),
    (170, 'Immaterielle Werte', 1),
    (1700, 'Patente, Know-how, Lizenzen, Rechte, Entwicklungen', 1),
    (1709, 'Wertberichtigungen Patente, Know-how, Lizenzen, Rechte, Entwicklungen', 1),
    (1770, 'Goodwill', 1),
    (1779, 'Wertberichtigungen Goodwill', 1),
    (180, 'Nicht einbezahltes Grund-, Gesellschafter- oder Stiftungskapital', 1),
    (1850, 'Nicht einbezahltes Aktien-, Stamm-, Anteilschein- oder Stiftungskapital', 1),
    (200, 'Verbindlichkeiten aus Lieferungen und Leistungen', 2),
    (2000, 'Verbindlichkeiten aus Lieferungen und Leistungen (Kreditoren)', 2),
    (2030, 'Erhaltene Anzahlungen', 2),
    (210, 'Kurzfristige verzinsliche Verbindlichkeiten', 2),
    (2100, 'Bankverbindlichkeiten', 2),
    (2120, 'Verbindlichkeiten aus Finanzierungsleasing', 2),
    (2140, 'Übrige verzinsliche Verbindlichkeiten', 2),
    (220, 'Übrige kurzfristige Verbindlichkeiten', 2),
    (2200, 'Geschuldete MWST (Umsatzsteuer)', 2),
    (2201, 'Abrechnungskonto MWST', 2),
    (2206, 'Verrechnungssteuer', 2),
    (2208, 'Direkte Steuern', 2),
    (2210, 'Sonstige kurzfristige Verbindlichkeiten', 2),
    (2261, 'Beschlossene Ausschüttungen', 2),
    (2270, 'Sozialversicherungen und Vorsorgeeinrichtungen', 2),
    (2279, 'Quellensteuer', 2),
    (230, 'Passive Rechnungsabgrenzungen und kurzfristige Rückstellungen', 2),
    (2300, 'Noch nicht bezahlter Aufwand', 2),
    (2301, 'Erhaltener Ertrag des Folgejahres', 2),
    (2330, 'Kurzfristige Rückstellungen', 2),
    (240, 'Langfristige verzinsliche Verbindlichkeiten', 2),
    (2400, 'Bankverbindlichkeiten', 2),
    (2420, 'Verbindlichkeiten aus Finanzierungsleasing', 2),
    (2430, 'Obligationenanleihen', 2),
    (2450, 'Darlehen', 2),
    (2451, 'Hypotheken', 2),
    (250, 'Übrige langfristige Verbindlichkeiten', 2),
    (2500, 'Übrige langfristige Verbindlichkeiten (unverzinslich)', 2),
    (260, 'Rückstellungen sowie vom Gesetz vorgesehene ähnliche Positionen', 2),
    (2600, 'Rückstellungen', 2),
    -- EK Aktiengesellschaft ===============
    (280, 'Grund-, Gesellschafter- oder Stiftungskapital', 2),
    (2800, 'Aktien-, Stamm-, Anteilschein- oder Stiftungskapital', 2),
    (290, 'Reserven und Jahresgewinn oder Jahresverlust', 2),
    (2900, 'Gesetzliche Kapitalreserve', 2),
    (2930, 'Reserve für eigene Kapitalanteile', 2),
    (2940, 'Aufwertungsreserve', 2),
    (2950, 'Gesetzliche Gewinnreserve', 2),
    (2960, 'Freiwillige Gewinnreserven', 2),
    (2970, 'Gewinnvortrag oder Verlustvortrag', 2),
    (2979, 'Jahresgewinn oder Jahresverlust', 2),
    (2980, 'Eigene Aktien, Stammanteile oder Anteilscheine (Minusposten)', 2);
    -- EK Einzelunternehmen ===============
    -- (2800, 'Eigenkapital zu Beginn des Geschäftsjahres', 2),
    -- (2820, 'Kapitaleinlagen und Kapitalrückzüge', 2),
    -- (2850, 'Privat', 2),
    -- (2891, 'Jahresgewinn oder Jahresverlust', 2);
    -- EK Personengesellschaft ===============
    -- (2800, 'Eigenkapital Gesellschafter A zu Beginn des Geschäftsjahres', 2),
    -- (2810, 'Kapitaleinlagen und Kapitalrückzüge Gesellschafter A', 2),
    -- (2820, 'Privat Gesellschafter A', 2),
    -- (2831, 'Jahresgewinn oder Jahresverlust Gesellschafter A', 2),
    -- (2850, 'Eigenkapital Kommanditär A zu Beginn des Geschäftsjahres', 2),
    -- (2860, 'Kapitaleinlagen und Kapitalrückzüge Kommanditär A', 2),
    -- (2870, 'Privat Kommanditär A', 2),
    -- (2881, 'Jahresgewinn oder Jahresverlust Kommanditär A', 2);
