name: Deploy docs to GitHub Pages

defaults:
    run:
        working-directory: ./docs

permissions:
    contents: write

on:
    push:
        branches:
            - main
        # Review gh actions docs if you want to further define triggers, paths, etc
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
    deploy:
        name: Deploy docs to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm
                  cache-dependency-path: "./docs/package-lock.json"

            - name: Install dependencies
              run: npm ci
            - name: Set credentials
              run: |
                  git config --global user.email ${{ secrets.EMAIL }}
                  git config --global user.name mnaray
                  git remote set-url origin https://mnaray:${{ secrets.GH_PAT }}@github.com/mnaray/CaptureTheFlag.git
            - name: Deploy website
              run: GIT_USER=mnaray GIT_PASS=${{ secrets.GH_PAT }} npm run deploy
